import Head from 'next/head'
import Link from 'next/link';

import Layout from '@components/Layout';
import Header from '@components/Header';
import Container from '@components/Container';
import Button from '@components/Button';

import { buildImage } from '@lib/cloudinary';

import styles from '@styles/Page.module.scss'

import { 
  ApolloClient,
  InMemoryCache,
  gql, 
  } from '@apollo/client';




export default function Category({ category, products }) {

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>{category.name}</h1>
        <h2>Products</h2>
        <ul className={styles.products}>
          {products?.map(product => {
            const imageURL = buildImage(product.image.public_id).toURL()
            return( 
          <li key={product.id}>
            <Link href={`/products/${product.slug}`}>
              <a>
                <div className={styles.productImage}>
                <img width='900' height='900' src={imageURL} alt="" />
                </div>
                <h3 className={styles.productTitle}>
                  {product.name}
                </h3>
                <p className={styles.productPrice}>
                {product.price.toFixed(2)}$
                </p>
              </a>
            </Link>
            <p>
              <Button
                 className="snipcart-add-item"
                 data-item-id={product.id}
                 data-item-price={product.price}
                 data-item-image={product.image.url}
                 data-item-name={product.name}
                 data-item-url={`/products/${product.slug}`}
              >
                Add to Cart
              </Button>
            </p>
            
          </li>
              )
            })}
        </ul>
      </Container>
    </Layout>
  )
}


export async function getStaticPaths() {

  const client = new ApolloClient({
    uri: 'https://api-eu-west-2.hygraph.com/v2/cl94h07cc52ae01uke8ms0jxr/master',
    cache: new InMemoryCache(),
  });

  const data = await client.query({
    query: gql`
    query CategoryPage {
      categories {
        id
        slug
      }
    }
    `
  })

  console.log(data)
  const paths = data.data.categories.map(category => {
    return {
      params: {
        categorySlug: category.slug
      }
    }
  })

  return {
    paths,
    fallback: false
  }
}

export async function getStaticProps({ params }) {

  const client = new ApolloClient({
    uri: 'https://api-eu-west-2.hygraph.com/v2/cl94h07cc52ae01uke8ms0jxr/master',
    cache: new InMemoryCache(),
  });

  const data = await client.query({
    query: gql`
    query CategoryAssets($slug: String = "") {
      category(where: {slug: $slug}) {
        id
        name
        slug
        products {
          id
          image
          name
          price
          slug
        }
      }
    }
    
    `,
    variables: {
      slug: params.categorySlug
    }
  })

 const category = data.data.category
 console.log(data)
  return {
    props: {
      category,
      products: category.products
    }
  }
}